name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_call:

env:
  REGISTRY: docker.io
  IMAGE_NAME: georgjung/nginx-brotli

jobs:
  build:
    strategy:
      matrix:
        include:
          - tag: mainline
            dockerfile: Dockerfile
            platforms: linux/amd64,linux/arm64
          - tag: mainline-alpine
            dockerfile: Dockerfile.alpine
            platforms: linux/amd64,linux/arm64
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: ${{ matrix.dockerfile }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
      push: false