name: Regular base image update check

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BASE_IMAGE: nginx:mainline

jobs:
  check_base_image_updated:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      image-needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Docker Image Update Checker
        id: check
        uses: georg-jung/docker-image-update-checker@main
        with:
          base-image: ${{ env.BASE_IMAGE }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:mainline
          github_token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true
  call_rebuild:
    needs: check_base_image_updated
    if: ${{ needs.check_base_image_updated.outputs.image-needs-updating == 'true' }}
    uses: ./.github/workflows/build.yml
