name: Cron base image update check

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1,13 * * *'

env:
  IMAGE_NAME: georgjung/nginx-brotli
  BASE_IMAGE: nginx

jobs:
  cron-check-matrix:
    strategy:
      matrix:
        include:
          - tag: mainline
            dockerfile: Dockerfile
            platforms: linux/amd64,linux/arm64
          - tag: mainline-alpine
            dockerfile: Dockerfile.alpine
            platforms: linux/amd64,linux/arm64
    uses: ./.github/workflows/rebuild-if-required.yml
    with:
      dockerfile: ${{ matrix.dockerfile }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
    secrets: inherit

  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: gautamkrishnar/keepalive-workflow@v2
