name: Regular base image update check

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1,13 * * *'

env:
  IMAGE_NAME: georgjung/nginx-brotli
  BASE_IMAGE: nginx

jobs:
  check_base_image_updated:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      images-need-updating: ${{ steps.check1.outputs.needs-updating == 'true' || steps.check2.outputs.needs-updating == 'true' }}
    steps:
      - name: Docker Image Update Checker mainline
        id: check1
        uses: georg-jung/docker-image-update-checker@main
        with:
          base-image: ${{ env.BASE_IMAGE }}:mainline
          image: ${{ env.IMAGE_NAME }}:mainline
          verbose: true
      - name: Docker Image Update Checker mainline-alpine
        id: check2
        uses: georg-jung/docker-image-update-checker@main
        with:
          base-image: ${{ env.BASE_IMAGE }}:mainline-alpine
          image: ${{ env.IMAGE_NAME }}:mainline-alpine
          verbose: true
  call_rebuild:
    needs: check_base_image_updated
    if: ${{ needs.check_base_image_updated.outputs.images-need-updating == 'true' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
