name: Base image update check

on:
  workflow_call:
    inputs:
      tag:
        description: 'Docker tag to build, e.g. mainline or mainline-alpine'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile in nginxinc/docker-nginx/master/modules/ to use'
        required: true
        type: string
      platforms:
        description: 'Platforms to rebuild, e.g. "linux/amd64", "linux/arm64", "linux/amd64,linux/arm64"'
        required: true
        type: string

env:
  IMAGE_NAME: georgjung/nginx-brotli
  BASE_IMAGE: nginx

jobs:
  check_base_image_updated:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      images-need-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Image Update Checker ${{ inputs.tag }}
        id: check
        uses: lucacome/docker-image-update-checker@f97e2a3cdbf2d8f9788fb87081a76542645a4252 # v3.1.1
        with:
          base-image: ${{ env.BASE_IMAGE }}:${{ inputs.tag }}
          image: ${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          platforms: ${{ inputs.platforms }}
  call_rebuild:
    needs: check_base_image_updated
    if: ${{ needs.check_base_image_updated.outputs.images-need-updating == 'true' }}
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ inputs.tag }}
      dockerfile: ${{ inputs.dockerfile }}
      platforms: '${{ inputs.platforms }}'
      push: true
    secrets: inherit
